### ISSUE TITLE
Fix header view for mobile

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/ketarasedar-web#22]
<img width="452" alt="Screenshot 2022-08-22 at 2 13 12 PM" src="https://user-images.githubusercontent.com/30463117/185851417-5aed0ca6-0011-448a-924d-3006a969802a.png">

**Comment by russel0907** [comment]
![APAM-Official-Website](https://user-images.githubusercontent.com/94702093/185855385-d17ee133-3803-4beb-9901-41fa790b47e8.png)
